# couldn't get r-base, r-ver, r-devel ... to behave.
# so went with r-ci (https://github.com/eddelbuettel/r-ci).

kind: pipeline
type: docker
name: r-ci (light)

steps:
- name: build 'n check
  image: rocker/r-bspm:20.04
  commands:
  - wget https://eddelbuettel.github.io/r-ci/run.sh && chmod 0755 run.sh
  - ./run.sh bootstrap
  - apt-get install -y --no-install-recommends libgeos-dev
  - ./run.sh install_deps
  - export _R_CHECK_FORCE_SUGGESTS_="false"; ./run.sh run_tests
